### ISSUE TITLE
Generate artifact doesn't seem to do anything

### ISSUE THREAD

**Issue by danyork** [digitalcube/shifter-static-local#5]
I have Shifter-local running on my MacBookPro.  When I go into the WordPress dashboard, I see that a Shifter menu is available. So I choose "Generate artifact".  It then gives me the warnings as it does in regular Shifter that generating the artifact will cause me not to be able to work in WordPress.  So I click on the OK button and I get the message that an artifact is being generated and to check the Shifter dashboard:

<img width="270" alt="shifter-local-where-is-dashboard" src="https://user-images.githubusercontent.com/41662/59970198-7c84fc80-9560-11e9-88f5-d28f727d6e44.png">

However...

1. I don't have any Shifter dashboard to check (that I can find).
2. After I dismiss the dialog box, I can continue using WordPress.
3. I can't find any sign on my disk that an "artifact" was created.

Is this functionality supposed to work on Shifter-local?   If so, it didn't work for me.

If **NOT** supposed to work, then I would recommend documenting that in the Github documentation so that people don't expect it to work (yet, anyway).

**Comment by sawanoboly** [comment]
Generate artifact Shifter-local is to check the operation of WordPress in almost the same environment as Shifter. Generate artifact button works only on Shifter platform.

> If NOT supposed to work, then I would recommend documenting that in the Github documentation so that people don't expect it to work (yet, anyway).


Thanks for the feedback, we will update the README.

**Comment by sawanoboly** [comment]
https://github.com/getshifter/shifter-local/commit/fbf85c84c37bf72b8d6490ad306265545ca0a184

I've updated README. Thanks 😃
